id: PA89B8CE3
initial_creation_type: input
source_metadata:
  title: Autobiography of sTag tshang lo tsā ba Shes rab rin chen (1405–1477)
  author: stag tshang lo tsA ba shes rab rin chen/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2020-08-03); revision in process, no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre; This text was published by the Paltsek
    Research Institute. (src)
  - Text input:dpal brtsegs bod yig dpe rnying zhib 'jug khang / (Lhasa) (eds)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:dpal brtsegs bod yig dpe rnying zhib 'jug khang / (eds)
  text_witnesses: https://sakyaresearch.org/sources/177
  bases:
    ba20:
      title: Autobiography of sTag tshang lo tsā ba Shes rab rin chen (1405–1477)
      order: 1
      base_file: ba20.txt
created_at: '2022-04-15T18:43:45.218388'
last_modified_at: '2022-04-15T18:43:45.218396'
quality: null
